version: "2"

services:
  web:
      build: .
      links:
          - postgres
      ports:
          - 8080:8080
  postgres:
      image: postgres
      environment:
          - POSTGRES_USER=root
      ports:
          - "5432:5432"
